import http.client
import json

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task-3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

def getCountriesList():
    connect = http.client.HTTPSConnection("vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com")

    headers = {
        'x-rapidapi-key': "84ddb881f1mshe52cf4b1b8fbde2p1665f2jsnc71b246a3a81",
        'x-rapidapi-host': "vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com"
        }

    connect.request("GET", "/api/npm-covid-data/", headers=headers)

    res = connect.getresponse()
    data = res.read()

    return list(json.loads(data.decode("utf-8")))

def getCountryStat(CountryIdentifyer):

    conn = http.client.HTTPSConnection("vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com")

    headers = {
        'x-rapidapi-key': "84ddb881f1mshe52cf4b1b8fbde2p1665f2jsnc71b246a3a81",
        'x-rapidapi-host': "vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com"
        }

    conn.request("GET", "/api/covid-ovid-data/sixmonth/" + CountryIdentifyer, headers=headers)

    res = conn.getresponse()
    data = res.read()

    if data.decode("utf-8") == '[]':
        CountryList = getCountriesList()
        for i in range(len(CountryList)):
            if str(dict(CountryList[i]).get("TwoLetterSymbol")).lower() == CountryIdentifyer.lower() or str(dict(CountryList[i]).get("Country")).lower() == CountryIdentifyer.lower():
                return list(getCountryStat(dict(CountryList[i]).get("ThreeLetterSymbol")))
        return ""
    else:
        return list(json.loads(data.decode("utf-8")))

class Ui_MainWindow(object):
    def createLabels(self, CountriesList):
        resoultLabelList = []

        for i in range(len(CountriesList)):
            resoultLabelList.append(QtWidgets.QLabel(self.scrollAreaWidgetContents))
            resoultLabelList[i].setMinimumHeight(20)
            resoultLabelList[i].setObjectName("CountryLabel" + str(i))
            resoultLabelList[i].setText(dict(CountriesList[i]).get("Country")) # temp
        return resoultLabelList

    def setupUi(self, MainWindow):
        print("jopa")
        MainWindow.setObjectName("Covid-19 countries status")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(219, 36, 571, 560))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 122))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())

        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")

        #self.CountriesLabelList.append(QtWidgets.QLabel(self.scrollAreaWidgetContents))
        #self.CountriesLabelList[0].setMinimumSize(QtCore.QSize(0, 20))
        #self.CountriesLabelList[0].setObjectName("label")

        #self.verticalLayout.addWidget(self.label)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(10, 50, 201, 41))
        self.searchButton.setObjectName("searchButton")

        self.searchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLine.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.searchLine.setObjectName("searchLine")

        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(10, 110, 201, 41))
        self.resetButton.setObjectName("resetButton")
        self.resetButton.clicked.connect(self.ResetPressed)

        self.scrollArea.raise_()
        self.searchLine.raise_()
        self.resetButton.raise_()
        self.searchButton.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #for i in self.CountriesLabelList:
            #i.setText(_translate("MainWindow", "TextLabel"))
        #self.label.setText(_translate("MainWindow", "TextLabel"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))

    def ResetPressed(self):
        #clearing vertical layout:
        for i in reversed(range(self.verticalLayout.count())): 
            self.verticalLayout.itemAt(i).widget().setParent(None)
        
        #set new widgets to layout:
        self.CountriesLabelList = self.createLabels(getCountriesList())
        for i in range(len(self.CountriesLabelList)):
            self.verticalLayout.addWidget(self.CountriesLabelList[i])



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())